### ISSUE TITLE
Controller not working anymore in 2.1.0 (XBOX Wireless Controller, M2 Macbook Pro, Sonoma)

### ISSUE THREAD

**Issue by TwentyWasHere** [unknownskl/xbox-xcloud-client#1118]
### Describe the bug

The controller shows up in Greenlight's setting once I press a button, so Greenlight at least sees it. It works also fine when I test it with Chrome on https://hardwaretester.com/gamepad. And it shows properly under MacOS's controller settings. 

But when a stream is started on the local network no input from the controller is sent to the console. If I revert back to 2.0.1 the controller works instantly again. 

It makes no difference if I add Input Monitoring to Privacy & Security for Greenlight or not. Neither does it make a difference if I start the app as a user or from the shell using sudo. 2.0.1 works, 2.1.0 doesn't anymore for me.

I did no other change anything beside upgrading the app. Controller not working. Downgrading working again. Currenly this is reproducible on my end.

### To Reproduce

Start a stream, no input sent to the console.

### Expected behavior

Start a stream. input sent to console.

### Environment

```markdown
Version: Greenlight 2.1.0
OS: MacOS Sonoma 14.2.1
PC: MacBook Pro
Console: Series X
Controller: XBox Wireless Controller
Controller Connection: Bluetooth (cable never worked for me)
Network: LAN, everything cabled
```

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by SanteR1** [comment]
on Steam Deck also does not work control

**Comment by PJ1UP** [comment]
I have the same issue

**Comment by dhedegaard** [comment]
Same issue, also it seems the controller is detected under "Settings" -> "Input". But does not work when connected to an xbox:

<img width="849" alt="image" src="https://github.com/unknownskl/greenlight/assets/591276/befc2cb0-57e3-497b-98f0-bde4b609cd31">

**Comment by I-am-future-busylessman** [comment]
Kind of same issue with Xbox Elite 2 controller, but app doesn't even see it
MacOS Sonoma M2 Max

**Comment by chaseace000** [comment]
Using steamdeck, updated to version 2.1.0. Both steamdeck buttons and dualsense controller not working in Game Mode (still working in Desktop Mode).  Deleted flatpak and settings, removed and readded to steam, and still had an issue. 
Reverted to previous version 2.0.1 and it worked in Game Mode again.

**Comment by thaifoodninja** [comment]
windows client as well, using xbox controller isn't working

**Comment by unknownskl** [comment]
Yep, confirmed. Thanks for letting know! The issue seems to be in the old gamepad driver. Will push a new version with this bug fixed soon.

**Workaround**
In the Settings, on the Input page there is an option to use the new gamepad driver. Please enable that and the controller should start working again.

**Comment by shanafan** [comment]
I enabled the new gamepad driver, which allowed me to use the Steam Deck’s buttons. However, for some odd reason, it doesn’t seem to detect the left trackpad on the Steam Deck anymore.

**Comment by hanshaozi** [comment]
After the update, the Steam Deck controller became unresponsive when linked to Xbox.

**Comment by TwentyWasHere** [comment]
Can confirm that using the suggested option works.

**Comment by slippy5140** [comment]
after the workaround posted above, works perfect

**Comment by shanafan** [comment]
> after the workaround posted above, works perfect

Are you on Steam Deck? Left trackpad isn’t working.

**Comment by uhnoneemus** [comment]
I had to rollback to prior version. It is working fine.

**Comment by slippy5140** [comment]
> > after the workaround posted above, works perfect
> 
> Are you on Steam Deck? Left trackpad isn’t working.

now that you mention this yeah left trackpad dosent work. i noticed that

**Comment by sevenb90** [comment]
I can confirm that the workaround works for Steam Deck. But binding the "N" Key (Guide Button) to one of the Steam Deck Back-Buttons (L4/L5, R4/R5) doesn't work.

I'm not a 100% sure if this is a related issue because I haven't used Greenlight for a long time.

**Comment by slippy5140** [comment]
> I can confirm that the workaround works for Steam Deck. But binding the "N" Key (Guide Button) to one of the Steam Deck Back-Buttons (L4/L5, R4/R5) doesn't work.
> 
> I'm not a 100% sure if this is a related issue because I haven't used Greenlight for a long time.

alright thank you

**Comment by shanafan** [comment]
> I can confirm that the workaround works for Steam Deck. But binding the "N" Key (Guide Button) to one of the Steam Deck Back-Buttons (L4/L5, R4/R5) doesn't work.
> 
> I'm not a 100% sure if this is a related issue because I haven't used Greenlight for a long time.

Yeah that’s the issue. No way to access the Xbox Guide and over remote play now. Have to pull out a second controller and press the guide button there 😂

**Comment by unknownskl** [comment]
It's probably not widely known but you can also press the view + menu (also known as select + start) to open the nexus menu. 

Eta for the fix is going to be in +- 24 hours

**Comment by unknownskl** [comment]
Version 2.1.1 has been released and should contain a fix for the controller. Additionally the N button is fixed on the new Gamepad driver. Please test it and let me know if it fixes the problem on your side too.

**Comment by Zombiz666** [comment]
> Version 2.1.1 has been released and should contain a fix for the controller. Additionally the N button is fixed on the new Gamepad driver. Please test it and let me know if it fixes the problem on your side too.

2.1.1 on Steam Deck now work fine, thanks.

**Comment by kingblah** [comment]
Controls still not working for me at all I'm afraid. "No controller detected' - fresh install of 2.1.1 - trying to use built in steam deck controls. 
Maybe I'm doing one of these wrong:
- It's in desktop mode. Maybe it doesn't work with the controller in desktop mode, and I should be adding it to game mode instead? (I tried this and the controls don't work still, but maybe I did it wrong. I just used 'add non-steam game')
- Maybe it's designed to use an external controller only, and the steam deck controls themselves don't work?
