### ISSUE TITLE
[Bug]  Failed to start new stream

### ISSUE THREAD

**Issue by K-ruze** [unknownskl/xbox-xcloud-client#1192]
### Describe the bug

Cant start stream was working fine for a while and now instantly receive this error when attempting to start stream tried reinstalling, restarting and deleting all program files restarted console, internet etc Xbox Remote play works fine 

Failed to start new stream. Error details:{"url":"/v5/sessions/home/play","status":401,"body":""}

### To Reproduce

1. Start Greenlight
2. Sign in
3. Console found
4. Start stream
5. Error

### Expected behavior

Stream to start

### Environment

```markdown
- OS: Windows
- Device: PC
- Greenlight version: 2.2.1
```

### Anything else?

![Greenlighterror](https://github.com/unknownskl/greenlight/assets/166666592/beb5cdc4-97f7-4bc2-8acc-5d6781787a85)

### New issue

- [X] I confirm that this is a new issue and not a duplicate

**Comment by unknownskl** [comment]
Thanks, issue is confirmed and a fix has been pushed. Need to test it first on other platforms before i can release it so expect a new release in +- 12 hours. (2 am right now, need to catch some sleep)

**Comment by Xukkorz** [comment]
I'm having the same issue on steam deck via the flatpak build fyi.

**Comment by TwentyWasHere** [comment]
Quickly compiled the app. Can confirm the pushed fix seems to work (MacOS 14.4.1, M2 MacBook Pro) for the changed authentication.

**Comment by kozi12** [comment]
![2FA2CDF3-8E69-45AA-8056-0929C617EACE_1_102_o](https://github.com/unknownskl/greenlight/assets/166682181/00773ee5-0333-4217-85f4-b14ecf61aac5)
same issue on steam deck

**Comment by jacknight** [comment]
Tried compiling the latest and get this now:
![Screenshot 2024-04-11 at 10 04 19 AM](https://github.com/unknownskl/greenlight/assets/581070/cd8b31bc-4a0b-4c87-96ee-f9d4361b78dc)

Macbook Pro (M1 Pro) Sonoma 14.5

**Comment by derbetakevin** [comment]
![2024-04-11 14 01 58](https://github.com/unknownskl/greenlight/assets/41595258/fb470352-8428-4be9-87cd-d5c58e355c40)
I have this Problem too

**Comment by unknownskl** [comment]
Version v2.3.0 has been released which should fix this issue. Please try it and let me know if the problem is also fixed on your end too. Flathub release should get published within +- 4 hours

**Comment by ferhat37ozkan** [comment]
Hey,

![image](https://github.com/unknownskl/greenlight/assets/41229777/b88374c3-d380-4588-9919-0fd08b09db6b)

Issue still occurs

**Comment by unknownskl** [comment]
> Hey,
> 
> ![image](https://private-user-images.githubusercontent.com/41229777/321631401-b88374c3-d380-4588-9919-0fd08b09db6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk1NzYsIm5iZiI6MTcxMjgzOTI3NiwicGF0aCI6Ii80MTIyOTc3Ny8zMjE2MzE0MDEtYjg4Mzc0YzMtZDM4MC00NTg4LTk5MTktMGZkMDhiMDlkYjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyNDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmQ3MmNiNTdkYTg0ZWFkNzQ3YzliOGZiMTM0NmY0YzYzYjgwNGI1ZmE3YzRlMWM5MWQyM2RjMDg4MTJhODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zCpEWADsGZitpGuYaCxVT13VKRDoOfsJ5NgU8y9Xmak)
> 
> Issue still occurs

Thanks, are you by any chance in a country where xCloud streaming is not supported? I might have to add a use case which skips retrieving the xCloud token if thats the case.

**Comment by jacknight** [comment]
> > Hey,
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/41229777/321631401-b88374c3-d380-4588-9919-0fd08b09db6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk1NzYsIm5iZiI6MTcxMjgzOTI3NiwicGF0aCI6Ii80MTIyOTc3Ny8zMjE2MzE0MDEtYjg4Mzc0YzMtZDM4MC00NTg4LTk5MTktMGZkMDhiMDlkYjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyNDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmQ3MmNiNTdkYTg0ZWFkNzQ3YzliOGZiMTM0NmY0YzYzYjgwNGI1ZmE3YzRlMWM5MWQyM2RjMDg4MTJhODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zCpEWADsGZitpGuYaCxVT13VKRDoOfsJ5NgU8y9Xmak)
> 
> > 
> 
> > Issue still occurs
> 
> 
> 
> Thanks, are you by any chance in a country where xCloud streaming is not supported? I might have to add a use case which skips retrieving the xCloud token if thats the case.

Unfortunately yes (Cyprus)

**Comment by ferhat37ozkan** [comment]
I'm from Türkiye.

**Comment by K-ruze** [comment]
Everything working as normal now on my end thank you

**Comment by Rhaegarlai** [comment]
> > Hey,
> > ![image](https://private-user-images.githubusercontent.com/41229777/321631401-b88374c3-d380-4588-9919-0fd08b09db6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk1NzYsIm5iZiI6MTcxMjgzOTI3NiwicGF0aCI6Ii80MTIyOTc3Ny8zMjE2MzE0MDEtYjg4Mzc0YzMtZDM4MC00NTg4LTk5MTktMGZkMDhiMDlkYjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyNDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmQ3MmNiNTdkYTg0ZWFkNzQ3YzliOGZiMTM0NmY0YzYzYjgwNGI1ZmE3YzRlMWM5MWQyM2RjMDg4MTJhODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zCpEWADsGZitpGuYaCxVT13VKRDoOfsJ5NgU8y9Xmak)
> > Issue still occurs
> 
> Thanks, are you by any chance in a country where xCloud streaming is not supported? I might have to add a use case which skips retrieving the xCloud token if thats the case.

Same problem in China,not support xCloud

**Comment by ferhat37ozkan** [comment]
xcloud not supporting here yet. Only Remote Play [Turkey-Türkiye]

**Comment by derbetakevin** [comment]
> I have this problem too

The problem has been solved with 2.3.0. Remote Play and xCloud works in Germany.

**Comment by Xukkorz** [comment]
Not sure if this is a timing issue or not but its not showing updated on flathub with the new revision and the flatpak won't install on steam deck for some reason. Are we expecting it updated on flathub or is someone else maintaining that page?

**Comment by DJGM1974** [comment]
The 401 bug may have been fixed, but since updating to v2.3.0 it's very laggy to stream from console with blurry picture.

(2018 Mac mini running macOS 13.6.3)

**Comment by komer83** [comment]
<img width="255" alt="Screenshot 2024-04-11 at 16 23 47" src="https://github.com/unknownskl/greenlight/assets/20399230/49a09958-48b9-42c4-b1c3-652c19b1b645">

**Comment by chandeeps** [comment]
Problem still persists with steam deck. Probably because xcloud is not available in India

![Screenshot_20240411_185948](https://github.com/unknownskl/greenlight/assets/16619272/e773c48b-45a4-472c-8154-ca3047e69c69)
![Failed to start error](https://github.com/unknownskl/greenlight/assets/16619272/cad6e478-36d6-47af-973b-a57ddb0c19f0)

**Comment by unknownskl** [comment]
Closing this issue as the 403 issue is a new bug. Lets continue the discussion of the bug related to non supported xCloud counties in #1193
