### ISSUE TITLE
[Bug] Greenlight hangs on launch, crashes Steam Deck

### ISSUE THREAD

**Issue by OldGnashburg** [unknownskl/xbox-xcloud-client#1502]
### Describe the bug

So I updated Greenlight or something recently and Greenlight just won't launch and eventually kicks me back to the game menu best case scenario, worse case scenario it hangs and I can't close it or do anything and the Steam Deck needs to be force shut down. Greenlight does work in Desktop mode. This was working within the last 3 or 4 months. Also won't launch via ES-DE.

### To Reproduce

Be on Steam Deck, latest version Greenlight, latest Steam Deck updates. Have Greenlight added menu. Launch game.

### Expected behavior

I launch Greenlight, the menu shows up. I play my XBOX.

### Environment

```markdown
- OS: SteamOS
- Device: Steam Deck
- Greenlight version: latest. 2.3.3?
```

### New issue

- [x] I confirm that this is a new issue and not a duplicate

**Comment by TheBoxyBear** [comment]
Encountering the same issue on the SteamOS stable branch. Although I'm a new user so don't have experience of it working on previous versions.

**Comment by unknownskl** [comment]
I think this is related to issue #1488. Will try to get a new updated version released this week.

**Comment by unknownskl** [comment]
v2.4.0 has been released with a new authentication mode which should fix this issue. Please try it out and let me know if it works for you

**Comment by OldGnashburg** [comment]
Application still hangs steam deck when launching from game mode. Need to force power off because it won't launch, it won't close, I can't run anything else.
Launching from Desktop Mode works just fine though.

**Comment by unknownskl** [comment]
> Application still hangs steam deck when launching from game mode. Need to force power off because it won't launch, it won't close, I can't run anything else.
> Launching from Desktop Mode works just fine though.

On which version does this happen?

**Comment by OldGnashburg** [comment]
2.4.1 I believe. Latest.
